--!strict
-- NVGN.Clean — boundaries v2: raycast-derived edges, closed by line intersection
--
--   Nodes are a selection mask and a connectivity graph. Never geometry.
--   Part geometry is the only source of edge lines.
--
-- DERIVATION. One horizontal ray from each standable node into the blocked
-- direction, and the engine hands over the geometry: Position (a point exactly
-- on the blocking surface), Normal (its plane), Instance (the blocker). No
-- isBlock gate — Unions, MeshParts and Terrain return a normal like anything
-- else. Origins are live nodes that passed LocalGrid's clearance probe, so
-- they are outside every collider by construction and the engine's
-- inside-origin trap cannot fire. The ray both classifies and measures.
--
-- EVERY class is a plane pair now, so there is a single code path:
--
--   wall/seam  {surface the ray hit}                  ∩ {floor top}
--   dropoff    {floor part's own rim plane}           ∩ {floor top}
--   tier       {ceiling plane pushed down by crawl h} ∩ {floor top}
--
-- The last two used to be lattice polylines. `dropoff` is ~60% of all
-- boundary length, so leaving it on the lattice would have walked the
-- staircase back into the mesh through polygonization. `tier` (a node whose
-- neighbour is dead from overhead cover, with nothing blocking at body
-- height) has no vertical face anywhere — but the locus where headroom equals
-- the crawl minimum is exactly the ceiling plane translated down by that
-- minimum, which is a plane like any other.
--
-- CLOSURE. Runs are LINES; the sample mask only hints which portion is real.
-- Vertices come from intersecting a floor's lines with each other, never from
-- sample positions, and endpoints snap along their own line to the nearest
-- such vertex. Overshoot trims back and undershoot extends forward — the same
-- operation, landing on the identical point — so a corner closes because two
-- edges share one computed vertex, not because two measured endpoints were
-- welded. The surviving tolerance (`maxSnap`) only chooses WHICH vertex an
-- endpoint belongs to; it never moves the vertex. That is the difference from
-- v1's weld/mergeCollinear/extend passes, which all moved geometry.
--
-- Collinearity is identity, not tolerance: two runs share a line iff they were
-- generated by the same plane pair.

local LocalGrid = require(script.Parent:WaitForChild("LocalGrid"))

local Clean = {}

export type Sample = {
	grid: any,
	cell: any,
	dir: Vector3,          -- outward, in the floor's plane (a grid axis)
	mid: Vector3,          -- cell-edge midpoint, mask-space (never emitted)
	class: string,         -- "wall" | "seam" | "dropoff" | "tier"
	planeN: Vector3,       -- blocking/limiting plane normal
	planeP: Vector3,       -- a point on that plane
	source: Instance,      -- blocker, continued-onto surface, cover, or the floor itself
}
export type Edge = {
	a: Vector3, b: Vector3,
	class: string,
	floor: BasePart,
	source: Instance,
	outDir: Vector3,       -- in-plane, points away from the walkable side
	lineId: string,        -- same id => provably the same line
	X0: Vector3, D: Vector3,
	samples: number,
	closedA: boolean, closedB: boolean, -- endpoint sits on a computed vertex
	-- true = part of this edge stands in for a deferred neighbour's missing
	-- boundary, not measured geometry
	provisional: boolean?,
	-- endpoint is a handover into an overlapping neighbouring floor, not a hole
	handoverA: boolean?, handoverB: boolean?,
}
export type Config = {
	step: number?, rayHeights: {number}?, rayLen: number?, coverTol: number?,
	planeEps: number?, normalEps: number?, minRun: number?,
	maxSlope: number?, seamEps: number?, seamDrop: number?,
	maxTrim: number?, maxExtend: number?, vertexEps: number?, parallelEps: number?,
	coplanarEps: number?,
}

local DEFAULT = {
	step = 1,
	rayHeights = { 0.25, 0.75, 1.2 }, -- all below minClearance 1.5: origins in open air
	rayLen = 1.6,
	coverTol = 0.35,
	planeEps = 0.06,
	normalEps = 0.02,
	minRun = 0.5,
	maxSlope = 65,
	seamEps = 0.3,
	seamDrop = 2.0,
	-- Snapping is ASYMMETRIC, because the two directions have different
	-- justifications.
	--
	-- Pulling an endpoint IN is free: the run genuinely ends at the corner and
	-- anything past it was the mask's half-cell overshoot, so trimming can
	-- reach as far as it likes.
	--
	-- Pushing an endpoint OUT is a claim that boundary exists where no sample
	-- was found, and the only defensible reason is the mask's own quantization
	-- — half a cell, plus slack. A generous outward reach lets an end jump to
	-- whatever vertex happens to lie ahead, which is exactly how edges came to
	-- overshoot their platform by a full 2 studs into open space.
	maxTrim = 2.0,
	maxExtend = 0.75,
	-- A vertex is STRONG when every line forming it actually reaches it, rather
	-- than being extrapolated to get there. Reaching a real corner justifies a
	-- longer extension than guessing at a crossing in open space: the ramp-base
	-- corner below needs 1.07, while the bogus 2-stud overshoots were all to
	-- weak vertices no line reached.
	maxExtendStrong = 1.6,
	-- longest rim gap that will be bridged across a deferred (union/mesh) floor
	maxBridge = 24,
	vertexEps = 0.05,   -- cluster near-identical intersections (3 lines at a corner)
	parallelEps = 1e-3,
	-- Faces this close to coplanar are treated as ONE wall. Authored walls are
	-- built from several parts that are flush to a fraction of a stud; without
	-- this they yield parallel lines that can never meet. Resolved toward the
	-- walkable side, so the error is always conservative.
	coplanarEps = 0.5,
	-- |n_ceiling × n_floor| below this means the two planes are too close to
	-- parallel for their intersection to be trusted: the line's position blows
	-- up with a fraction of a degree of tilt. ~0.26 ≈ 15°.
	tierMinTilt = 0.26,
	-- How far past a floor's OWN rim to look for a neighbour that carries on.
	-- Cross-grid coverage (above) asks the LATTICE, one full step out, which
	-- silently assumes the neighbour's lattice is in phase with ours — exactly
	-- what is false between two parts at different yaws. Ask the geometry
	-- instead, a hair past the rim, where phase cannot enter.
	rimProbe = 0.05,
}

local UP = Vector3.new(0, 1, 0)

-- Keys must carry instance IDENTITY: `tostring(part)` returns the NAME, and
-- authored scenes reuse names freely (every "Pink" collapsed into one group).
local nextId = 0
local idOf: { [Instance]: number } = setmetatable({}, { __mode = "k" }) :: any
local function iid(inst: Instance): number
	local id = idOf[inst]
	if not id then nextId += 1; id = nextId; idOf[inst] = id end
	return id
end

local function merged(cfg): any
	local c = {}
	for k, v in pairs(DEFAULT) do c[k] = v end
	if cfg then for k, v in pairs(cfg) do if v ~= nil then c[k] = v end end end
	return c
end

local function q(x: number, eps: number): number
	return math.floor(x / eps + 0.5)
end

--------------------------------------------------------------------------
-- Cross-grid coverage (v2 stage 1)
--
-- Grids are per-part, so a node at part B's rim sees an "absent" neighbour
-- even where part A covers that spot at the same height. Those boundaries are
-- FICTIONAL and line-breaking: a false dropoff one row behind a real one puts
-- a branch or a jog into any polyline fit.
--------------------------------------------------------------------------

local function buildCover(data: any): { [string]: {Vector3} }
	local cover: { [string]: {Vector3} } = {}
	for _, g in pairs(data.grids) do
		for _, cell in ipairs(g.cells) do
			local k = string.format("%d:%d", math.floor(cell.pos.X), math.floor(cell.pos.Z))
			local b = cover[k]
			if not b then b = {}; cover[k] = b end
			b[#b + 1] = cell.pos
		end
	end
	return cover
end

local function covered(cover: any, p: Vector3, c: any): boolean
	local bx, bz = math.floor(p.X), math.floor(p.Z)
	local hTol = c.step * 0.5
	for dx = -1, 1 do
		for dz = -1, 1 do
			local b = cover[string.format("%d:%d", bx + dx, bz + dz)]
			if b then
				for _, qq in ipairs(b) do
					if math.abs(qq.Y - p.Y) <= c.coverTol
						and math.abs(qq.X - p.X) <= hTol and math.abs(qq.Z - p.Z) <= hTol then
						return true
					end
				end
			end
		end
	end
	return false
end

--------------------------------------------------------------------------
-- Stage 1 — frontier samples, one per (node, direction) pair.
--
-- Class belongs to the PAIR, not the node: a stair tread is a wall uphill and
-- a dropoff downhill simultaneously.
--------------------------------------------------------------------------

local function sampleFrontier(data: any, c: any): ({Sample}, any)
	local cover = buildCover(data)
	local samples: {Sample} = {}
	local stats = {
		fictional = 0, wall = 0, seam = 0, dropoff = 0, tier = 0,
		tierUnresolved = 0, fallbackSkipped = 0,
	}
	local crawlH = (data.config and data.config.minClearance) or 1.5

	for part, g in pairs(data.grids) do
		if g.fallback then
			stats.fallbackSkipped += 1
			continue
		end
		local dirs = { g.u, -g.u, g.v, -g.v }
		-- rim half-extent for each of those directions, for the dropoff planes
		local exts = { g.uExt, g.uExt, g.vExt, g.vExt }
		local rp = RaycastParams.new()
		rp.FilterType = Enum.RaycastFilterType.Exclude
		rp.FilterDescendantsInstances = { part } -- Terrain deliberately left in
		rp.IgnoreWater = true

		for _, cell in ipairs(g.cells) do
			for di, dir in ipairs(dirs) do
				local du = (di <= 2) and ((di == 1) and 1 or -1) or 0
				local dv = (di <= 2) and 0 or ((di == 3) and 1 or -1)
				local nk = string.format("%d:%d", cell.ui + du, cell.vi + dv)
				if g.index[nk] then continue end -- interior

				local mid = cell.pos + dir * (c.step * 0.5)
				local dead = g.deadIndex[nk]
				local nbrPos = cell.pos + dir * c.step

				if not dead and covered(cover, nbrPos, c) then
					stats.fictional += 1
					continue
				end

				local best: RaycastResult? = nil
				for _, h in ipairs(c.rayHeights) do
					local res = workspace:Raycast(cell.pos + UP * h, dir * c.rayLen, rp)
					if res and (not best or res.Distance < best.Distance) then best = res end
				end

				local class, planeN, planeP, source

				if best then
					local hit = best :: RaycastResult
					-- A hit within the walkability limit is not a wall face —
					-- the ray grazed a FLOOR. A clipramp's low end sits a hair
					-- under the ground, so the ray clips the ground's top and
					-- v1 called the ramp entry a wall. Flush contact with a
					-- traversable surface is CONTINUITY. Past seamEps it is a
					-- real lip: round 7 keeps that wall-from-below.
					local slope = math.deg(math.acos(math.clamp(hit.Normal:Dot(UP), -1, 1)))
					local dy = hit.Position.Y - cell.pos.Y
					class = (slope <= c.maxSlope and math.abs(dy) <= c.seamEps) and "seam" or "wall"
					planeN, planeP, source = hit.Normal, hit.Position, hit.Instance

				elseif dead then
					-- Killed by overhead cover with nothing blocking at body
					-- height. No vertical face exists — but the locus where
					-- headroom equals the crawl minimum IS the ceiling plane
					-- translated down by it.
					-- Where does crawlable space end under an overhang? At the
					-- overhang's own leading EDGE: this node has >= crawlH of
					-- headroom and its neighbour has less, so the cover must
					-- present a vertical face between them. Ask for it directly,
					-- from just above the crawl ceiling — the body-height fan
					-- passed underneath, which is why this landed here at all.
					local hi = workspace:Raycast(
						cell.pos + UP * (crawlH + 0.25), dir * c.rayLen, rp)
					if hi and math.abs(hi.Normal:Dot(UP)) < 0.5 then
						class = "tier"
						planeN, planeP, source = hi.Normal, hi.Position, hi.Instance
					else
						-- No side face (a bevelled or sloping soffit). Fall back
						-- to the locus where headroom equals crawlH, which is the
						-- ceiling plane translated down by it — but ONLY when the
						-- ceiling is far enough from parallel with the floor for
						-- that intersection to be conditioned. Near-parallel, the
						-- line's position explodes: this drew a yellow bar in
						-- open sky, tens of studs from any low ceiling.
						local ceil = nil
						if dead.killer then
							local rpCover = RaycastParams.new()
							rpCover.FilterType = Enum.RaycastFilterType.Include
							rpCover.FilterDescendantsInstances = { dead.killer }
							-- fired from BELOW the floor: the floor is not in the
							-- filter so it cannot block, and an origin two studs
							-- down is outside the cover, which a start point on
							-- the floor surface is not when the cover sits flush
							-- on it (the inside-origin trap, which swallowed all
							-- six of these on the first run)
							ceil = workspace:Raycast(dead.pos - UP * 2, UP * (2 + crawlH + 0.5), rpCover)
						end
						-- The hit must be an actual CEILING: strictly above the
						-- walkable surface and within the crawl band. This ray
						-- starts two studs under the floor, so a clipramp buried
						-- at its low end answers with its underside BELOW the
						-- floor — translating that down by the crawl height put
						-- the plane underground and threw the line 2.3 studs
						-- away from the cell that generated it, drawing yellow
						-- bars under open sky.
						local Fn = g.n or UP
						local dh = ceil and (ceil.Position.Y - cell.pos.Y) or -1
						if ceil and dh > 0.05 and dh <= crawlH + 0.05
							and ceil.Normal:Cross(Fn).Magnitude >= c.tierMinTilt then
							class = "tier"
							planeN = ceil.Normal
							planeP = ceil.Position - UP * crawlH
							source = ceil.Instance
						else
							stats.tierUnresolved += 1
							continue
						end
					end

				else
					-- Nothing blocks at body height. Before calling it a drop,
					-- look just below the rim: a ramp descending from a flush
					-- top edge is an ENTRY. The flush gate scopes this (round 6:
					-- a clipramp seams only where flush — you enter at its ends,
					-- never through its side mid-slope).
					local dres = workspace:Raycast(
						nbrPos + UP * c.seamEps, -UP * (c.seamEps + c.seamDrop), rp)
					if dres then
						local slope = math.deg(math.acos(math.clamp(dres.Normal:Dot(UP), -1, 1)))
						if slope <= c.maxSlope
							and math.abs(dres.Position.Y - cell.pos.Y) <= c.seamEps then
							class = "seam"
							planeN, planeP, source = dres.Normal, dres.Position, dres.Instance
						end
					end
					if not class then
						local rimP = (g.center :: Vector3) + dir * exts[di]
						-- Before claiming the world ends at this part's rim, look
						-- just PAST it. A neighbouring slab that carries on flush
						-- owns whatever boundary lies out there; our rim is then an
						-- internal overlap, and drawing it produces a duplicate
						-- line a fraction of a stud inside the real one and skewed
						-- by the angle between the two parts — a stub that no
						-- closure pass can reconcile, because it belongs to a
						-- different floor and a different line.
						--
						-- Cross-grid coverage cannot catch this. It samples one
						-- full step out, where the neighbour has already ended, and
						-- the neighbour's lattice carries no cell centre inside the
						-- narrow sliver that overhangs us. Geometry has no phase
						-- problem.
						--
						-- Only a MESHED neighbour may suppress us: a fallback
						-- (union/mesh) floor emits no edges of its own, so deferring
						-- to one would open a hole rather than move a line.
						local tPast = (rimP - cell.pos):Dot(dir) + c.rimProbe
						local past = workspace:Raycast(
							cell.pos + dir * tPast + UP * c.seamEps,
							-UP * (c.seamEps + c.seamDrop), rp)
						if past then
							local og = data.grids[past.Instance]
							local sl = math.deg(math.acos(math.clamp(past.Normal:Dot(UP), -1, 1)))
							if og and not og.fallback and sl <= c.maxSlope
								and math.abs(past.Position.Y - cell.pos.Y) <= c.seamEps then
								stats.fictional += 1
								continue
							end
						end
						-- A genuine ledge. The floor ENDS here, so the exact line
						-- is the part's own rim plane — which also fixes the
						-- lattice under-covering the rim when the part size is
						-- not a whole number of cells.
						class = "dropoff"
						planeN = dir
						planeP = rimP
						source = part
					end
				end

				stats[class] += 1
				samples[#samples + 1] = {
					grid = g, cell = cell, dir = dir, mid = mid, class = class,
					planeN = planeN, planeP = planeP, source = source,
				}
			end
		end
	end
	return samples, stats
end

--------------------------------------------------------------------------
-- Stage 2 — runs. One path for every class.
--
-- Group by (floor, source, plane): the plane itself, not a collinearity
-- tolerance. The group supplies only the EXTENT; the line is
-- {plane} ∩ {floor top}, which has no lattice term at all — the staircase is
-- not smoothed here, it is never generated.
--------------------------------------------------------------------------

local function intersectPlanes(N: Vector3, P: Vector3, Fn: Vector3, F0: Vector3)
	local D = N:Cross(Fn)
	if D.Magnitude < 1e-4 then return nil end -- plane parallel to the floor (a fold)
	D = D.Unit
	-- F0 is already on the floor plane (it is an average of surface points), so
	-- slide it within that plane until it satisfies the other plane.
	local R = F0
	local w = N - Fn * N:Dot(Fn)
	if w.Magnitude < 1e-4 then return nil end
	w = w.Unit
	local denom = N:Dot(w)
	if math.abs(denom) < 1e-4 then return nil end
	return R + w * (N:Dot(P - R) / denom), D
end

local function buildRuns(samples: {Sample}, c: any): {Edge}
	-- Pass A — bucket by (floor, class, plane orientation). Source is
	-- deliberately NOT in the key: two parts forming one continuous wall should
	-- produce one line, not two.
	local buckets: { [string]: {Sample} } = {}
	local border: {string} = {}
	for _, s in ipairs(samples) do
		local n = s.planeN
		local key = string.format("%d|%s|%d,%d,%d",
			iid(s.grid.part), s.class,
			q(n.X, c.normalEps), q(n.Y, c.normalEps), q(n.Z, c.normalEps))
		local b = buckets[key]
		if not b then b = {}; buckets[key] = b; border[#border + 1] = key end
		b[#b + 1] = s
	end

	-- Pass B — cluster near-coplanar planes within a bucket.
	--
	-- Authored walls are routinely built from several parts whose faces are
	-- flush to within a fraction of a stud but not exactly equal. Those produce
	-- parallel lines that can NEVER intersect, so no amount of corner-closure
	-- reaches them and the run ends sit a visible ~0.3 apart. Every one of the
	-- 170 remaining gaps on the test scene was this.
	--
	-- The cluster takes the most CONSERVATIVE offset — the plane furthest
	-- toward the walkable side (hit normals point back along the ray, so that
	-- is the maximum of N·P). An agent is then held a hair further from the
	-- wall than strictly necessary, which is the safe direction, and the jog
	-- disappears instead of becoming a sub-stud fragment.
	local groups: { [string]: {Sample} } = {}
	local order: {string} = {}
	for _, key in ipairs(border) do
		local list = buckets[key]
		local offs = {}
		for _, s in ipairs(list) do
			offs[#offs + 1] = s.planeN:Dot(s.planeP)
		end
		table.sort(offs)
		-- greedy chain: consecutive offsets within coplanarEps share a cluster
		local reps, cuts = {}, {}
		local start = 1
		for i = 2, #offs + 1 do
			if i > #offs or (offs[i] - offs[i - 1]) > c.coplanarEps then
				reps[#reps + 1] = offs[i - 1] -- max of the cluster = conservative
				cuts[#cuts + 1] = offs[i - 1]
				start = i
			end
		end
		for _, s in ipairs(list) do
			local d = s.planeN:Dot(s.planeP)
			local ci, rep = 1, reps[1]
			for k = 1, #cuts do
				if d <= cuts[k] + 1e-6 then ci, rep = k, reps[k]; break end
				ci, rep = k, reps[k]
			end
			local gkey = string.format("%s|c%d", key, ci)
			local b = groups[gkey]
			if not b then b = {}; groups[gkey] = b; order[#order + 1] = gkey end
			-- rebase this sample onto the cluster's representative plane
			s.planeP = s.planeP + s.planeN * ((rep :: number) - d)
			b[#b + 1] = s
		end
	end

	local edges: {Edge} = {}
	for _, key in ipairs(order) do
		local grp = groups[key]
		local g = grp[1].grid
		local Fn = g.n or UP
		local N, P, F0, DIR = Vector3.zero, Vector3.zero, Vector3.zero, Vector3.zero
		for _, s in ipairs(grp) do
			N += s.planeN; P += s.planeP; F0 += s.cell.pos; DIR += s.dir
		end
		local inv = 1 / #grp
		N = N.Unit; P *= inv; F0 *= inv

		local X0, D = intersectPlanes(N, P, Fn, F0)
		if not X0 then continue end
		X0 = X0 :: Vector3; D = D :: Vector3

		-- outward direction, exactly perpendicular to the line in the floor
		-- plane, oriented by where the samples were looking
		local outDir = D:Cross(Fn)
		if outDir.Magnitude < 1e-4 then outDir = DIR end
		outDir = outDir.Unit
		if outDir:Dot(DIR) < 0 then outDir = -outDir end

		local ts = {}
		for _, s in ipairs(grp) do ts[#ts + 1] = (s.mid - X0):Dot(D) end
		table.sort(ts)
		local half = c.step * 0.5
		local i = 1
		while i <= #ts do
			local j = i
			while j < #ts and (ts[j + 1] - ts[j]) <= c.step * 1.5 do j += 1 end
			edges[#edges + 1] = {
				a = X0 + D * (ts[i] - half), b = X0 + D * (ts[j] + half),
				class = grp[1].class, floor = g.part, source = grp[1].source,
				outDir = outDir, lineId = key, X0 = X0, D = D,
				samples = j - i + 1, closedA = false, closedB = false,
			}
			i = j + 1
		end
	end
	return edges
end

--------------------------------------------------------------------------
-- Stage 3 — closure.
--
-- The mask decided WHICH portion of each line is real, and it is wrong by up
-- to half a cell in both directions: it overshoots past a corner (the last
-- sample's half-cell extension) and undershoots before one (exposure trimming
-- killed the samples there). Both are fixed by the same move — snap the
-- endpoint along its own line onto a vertex computed from the lines
-- themselves. Nothing here invents a position; it only chooses among exact
-- intersections.
--------------------------------------------------------------------------

local function closeFloor(edges: {Edge}, g: any, Fn: Vector3, c: any, report: any)
	-- Candidate lines = the emitted edges, PLUS the floor part's four rim
	-- planes as virtual lines.
	--
	-- The rims matter because of a case edges alone cannot cover: where two
	-- slabs abut flush, cross-grid coverage correctly emits no boundary, so a
	-- wall crossing both floors has nothing to intersect against at the
	-- junction and both runs stop at mask precision — a visible ~0.4 stud gap.
	-- The rim plane exists geometrically whether or not an edge was emitted on
	-- it, and both slabs' rims coincide there, so the two runs snap to the same
	-- computed point. Virtual lines are vertex SOURCES only; they are never
	-- emitted as boundary.
	type Cand = { X0: Vector3, D: Vector3, id: string, e: Edge? }
	local cands: {Cand} = {}
	for _, e in ipairs(edges) do
		cands[#cands + 1] = { X0 = e.X0, D = e.D, id = e.lineId, e = e }
	end
	if g and g.center and g.uExt and g.vExt then
		local rims = {
			{ n = g.u, ext = g.uExt }, { n = -g.u, ext = g.uExt },
			{ n = g.v, ext = g.vExt }, { n = -g.v, ext = g.vExt },
		}
		for ri, r in ipairs(rims) do
			local X0, D = intersectPlanes(r.n, g.center + r.n * r.ext, Fn, g.center)
			if X0 then
				cands[#cands + 1] = { X0 = X0 :: Vector3, D = D :: Vector3, id = "rim" .. ri, e = nil }
			end
		end
	end

	-- 1. every pairwise intersection of non-parallel candidate lines
	local verts: {Vector3} = {}
	for i = 1, #cands - 1 do
		local ci = cands[i]
		for j = i + 1, #cands do
			local cj = cands[j]
			if ci.id ~= cj.id then
				local cross = ci.D:Cross(cj.D):Dot(Fn)
				if math.abs(cross) > c.parallelEps then
					-- solve X0i + t*Di = X0j + s*Dj within the floor plane
					local rel = cj.X0 - ci.X0
					local t = rel:Cross(cj.D):Dot(Fn) / cross
					local p = ci.X0 + ci.D * t
					-- keep only vertices near the extent of every candidate that
					-- HAS one: two lines always meet somewhere, and a meeting
					-- 80 studs away is not a corner. Rim lines have no extent.
					-- `near` = close enough to consider at all.
					-- `reaches` = that line's own extent already covers the
					-- point, so the corner is real rather than extrapolated.
					local function judge(cd: Cand): (boolean, boolean)
						local e = cd.e
						if not e then return true, false end -- rim: unbounded, never counts as reaching
						local ta = (e.a - e.X0):Dot(e.D)
						local tb = (e.b - e.X0):Dot(e.D)
						if ta > tb then ta, tb = tb, ta end
						local tp = (p - e.X0):Dot(e.D)
						local near = tp >= ta - c.maxExtendStrong and tp <= tb + c.maxExtendStrong
						local reaches = tp >= ta - c.vertexEps and tp <= tb + c.vertexEps
						return near, reaches
					end
					local nearI, reachI = judge(ci)
					local nearJ, reachJ = judge(cj)
					if nearI and nearJ then
						verts[#verts + 1] = { p = p, strong = (reachI or reachJ) }
					end
				end
			end
		end
	end

	-- 2. cluster coincident intersections (3+ surfaces meeting at one corner)
	local clustered: { { p: Vector3, strong: boolean } } = {}
	for _, v in ipairs(verts) do
		local hit = false
		for k, cv in ipairs(clustered) do
			if (cv.p - v.p).Magnitude <= c.vertexEps then
				clustered[k] = { p = (cv.p + v.p) * 0.5, strong = cv.strong or v.strong }
				hit = true
				break
			end
		end
		if not hit then clustered[#clustered + 1] = v end
	end
	report.vertices += #clustered

	-- 3. snap each endpoint along its own line to the nearest vertex.
	-- Orientation first, so "outward" is well defined: a is the low end.
	for _, e in ipairs(edges) do
		local ta, tb = (e.a - e.X0):Dot(e.D), (e.b - e.X0):Dot(e.D)
		if ta > tb then
			e.a, e.b = e.b, e.a
			e.closedA, e.closedB = e.closedB, e.closedA
		end
	end
	for _, e in ipairs(edges) do
		local ta = (e.a - e.X0):Dot(e.D)
		local tb = (e.b - e.X0):Dot(e.D)
		local bestA, bestB = nil, nil
		local dA, dB = math.huge, math.huge
		for _, v in ipairs(clustered) do
			-- must lie ON this line, not merely near it
			local tp = (v.p - e.X0):Dot(e.D)
			if (e.X0 + e.D * tp - v.p).Magnitude <= c.vertexEps then
				local outBudget = c.maxExtend
				if v.strong then outBudget = c.maxExtendStrong end
				-- a: below is outward, above is inward. b: the reverse.
				local limA, limB
				if tp < ta then limA = outBudget else limA = c.maxTrim end
				if tp > tb then limB = outBudget else limB = c.maxTrim end
				local da, db = math.abs(tp - ta), math.abs(tp - tb)
				if da <= limA and da < dA then dA = da; bestA = tp end
				if db <= limB and db < dB then dB = db; bestB = tp end
			end
		end
		if bestA and bestB and bestA == bestB then
			-- degenerate: both ends want the same vertex, keep the nearer one
			if dA <= dB then bestB = nil else bestA = nil end
		end
		if bestA then e.a = e.X0 + e.D * bestA; e.closedA = true; report.snapped += 1 end
		if bestB then e.b = e.X0 + e.D * bestB; e.closedB = true; report.snapped += 1 end
	end

	-- 4. merge collinear runs that now abut, and drop what has collapsed.
	-- Same lineId means provably the same line, so this is exact.
	local byLine: { [string]: {Edge} } = {}
	for _, e in ipairs(edges) do
		local b = byLine[e.lineId]
		if not b then b = {}; byLine[e.lineId] = b end
		b[#b + 1] = e
	end
	local kept: {Edge} = {}
	for _, list in pairs(byLine) do
		table.sort(list, function(x, y)
			return (x.a - x.X0):Dot(x.D) < (y.a - y.X0):Dot(y.D)
		end)
		local cur: Edge? = nil
		for _, e in ipairs(list) do
			-- normalise direction so a < b along D
			local ta, tb = (e.a - e.X0):Dot(e.D), (e.b - e.X0):Dot(e.D)
			if ta > tb then
				e.a, e.b = e.b, e.a
				e.closedA, e.closedB = e.closedB, e.closedA
			end
			if not cur then
				cur = e
			else
				local cc = cur :: Edge
				local curEnd = (cc.b - cc.X0):Dot(cc.D)
				local eStart = (e.a - e.X0):Dot(e.D)
				local eEnd = (e.b - e.X0):Dot(e.D)
				if eStart <= curEnd + c.vertexEps and e.class == cc.class then
					if eEnd > curEnd then
						cc.b = e.b
						cc.closedB = e.closedB
					end
					cc.samples += e.samples
					report.mergedCollinear += 1
				else
					kept[#kept + 1] = cc
					cur = e
				end
			end
		end
		if cur then kept[#kept + 1] = cur :: Edge end
	end

	local final: {Edge} = {}
	for _, e in ipairs(kept) do
		if (e.b - e.a).Magnitude >= c.minRun then
			final[#final + 1] = e
		else
			report.dropped += 1
		end
	end
	return final
end

-- Closest approach between two 3D lines. Returns the parameter on the first
-- line and the gap between them.
local function closestApproach(X1: Vector3, D1: Vector3, X2: Vector3, D2: Vector3)
	local w = X1 - X2
	local b = D1:Dot(D2)
	local den = 1 - b * b
	if math.abs(den) < 1e-6 then return nil end -- parallel
	local d = D1:Dot(w)
	local e = D2:Dot(w)
	local t1 = (b * e - d) / den
	local t2 = (e - b * d) / den
	local p1 = X1 + D1 * t1
	local p2 = X2 + D2 * t2
	return t1, (p1 - p2).Magnitude
end

-- Cross-floor closure. Per-floor closure cannot fix an edge that ends where a
-- NEIGHBOURING part takes over — its partner line lives in another floor's set
-- — which is most of the remaining open ends. Two lines on different floors
-- rarely intersect exactly in 3D, so this uses closest approach and demands the
-- gap be within seamEps: still a computed point on the edge's own line, never a
-- weld that drags geometry toward a measured endpoint.
local function closeAcrossFloors(edges: {Edge}, c: any, report: any)
	for _, e in ipairs(edges) do
		for _, which in ipairs({ "a", "b" }) do
			local closedKey = (which == "a") and "closedA" or "closedB"
			if not (e :: any)[closedKey] then
				local tEnd = (((e :: any)[which] :: Vector3) - e.X0):Dot(e.D)
				-- same asymmetry as within a floor: `a` is the low end, so
				-- moving below it extends, and moving above it trims
				local tOther = (((which == "a") and e.b or e.a) - e.X0):Dot(e.D)
				local bestT, bestGap = nil, c.seamEps
				for _, o in ipairs(edges) do
					if o.floor ~= e.floor then
						local t, gap = closestApproach(e.X0, e.D, o.X0, o.D)
						-- NB: written as explicit branches on purpose. The
						-- `cond and X or Y` form silently returns Y whenever X
						-- is false, which here would hand an outward move the
						-- inward (2.0) budget — reintroducing exactly the
						-- over-extension this cap exists to prevent.
						local outward, sane = false, false
						if t then
							if which == "a" then
								outward = t < tEnd
								sane = t < tOther
							else
								outward = t > tEnd
								sane = t > tOther
							end
						end
						if t and sane and gap <= bestGap then
							local ta = (o.a - o.X0):Dot(o.D)
							local tb = (o.b - o.X0):Dot(o.D)
							if ta > tb then ta, tb = tb, ta end
							local p = e.X0 + e.D * t
							local tp = (p - o.X0):Dot(o.D)
							-- same strength rule as within a floor: if the
							-- partner's own extent already reaches the point,
							-- the corner is real and earns the longer budget
							local reaches = tp >= ta - c.vertexEps and tp <= tb + c.vertexEps
							local budget = c.maxExtend
							if reaches then budget = c.maxExtendStrong end
							local allow = c.maxTrim
							if outward then allow = budget end
							if tp >= ta - c.maxExtendStrong and tp <= tb + c.maxExtendStrong
								and math.abs(t - tEnd) <= allow then
								bestT, bestGap = t, gap
							end
						end
					end
				end
				if bestT then
					(e :: any)[which] = e.X0 + e.D * bestT
					;(e :: any)[closedKey] = true
					report.snappedCrossFloor += 1
				end
			end
		end
	end
end

-- Bridge gaps that exist only because a neighbouring floor is DEFERRED.
--
-- Where a block floor's rim is covered by a union/mesh floor, coverage
-- correctly emits no boundary — walkable surface really does continue. But
-- fallback floors produce no edges of their own, so the loop is left with a
-- hole and polygonization cannot decide inside from outside along it.
--
-- Both sides of such a gap lie on the SAME rim line (identical lineId), so
-- bridging is exact: the boundary follows the part's own rim, which walls the
-- un-meshed floor off. That is the conservative reading — agents will not path
-- onto a surface with no navmesh — and it disappears on its own once unions
-- emit boundaries, because the coverage will then be backed by real edges.
-- Marked `provisional` so nothing downstream mistakes it for measured geometry.
local function bridgeDeferred(edges: {Edge}, data: any, c: any, report: any): {Edge}
	local byLine: { [string]: {Edge} } = {}
	for _, e in ipairs(edges) do
		local b = byLine[e.lineId]
		if not b then b = {}; byLine[e.lineId] = b end
		b[#b + 1] = e
	end

	local function deferredFloorAt(p: Vector3): boolean
		for _, g in pairs(data.grids) do
			if g.fallback then
				for _, cell in ipairs(g.cells) do
					if (cell.pos - p).Magnitude < 1.5 then return true end
				end
			end
		end
		return false
	end

	local dead: { [Edge]: boolean } = {}
	for _, list in pairs(byLine) do
		for _, e in ipairs(list) do
			local ta, tb = (e.a - e.X0):Dot(e.D), (e.b - e.X0):Dot(e.D)
			if ta > tb then e.a, e.b = e.b, e.a end
		end
		table.sort(list, function(x, y)
			return (x.a - x.X0):Dot(x.D) < (y.a - y.X0):Dot(y.D)
		end)
		local cur: Edge? = nil
		for _, e in ipairs(list) do
			if not cur then
				cur = e
			else
				local cc = cur :: Edge
				local gap = (e.a - cc.b).Magnitude
				local bridgeable = gap > 0 and gap <= c.maxBridge and e.class == cc.class
				if bridgeable then
					for i = 1, 5 do
						if not deferredFloorAt(cc.b:Lerp(e.a, i / 6)) then
							bridgeable = false
							break
						end
					end
				end
				if bridgeable then
					cc.b = e.b
					cc.closedB = e.closedB
					cc.samples += e.samples
					cc.provisional = true
					dead[e] = true
					report.bridgedDeferred += 1
				else
					cur = e
				end
			end
		end
	end

	local out: {Edge} = {}
	for _, e in ipairs(edges) do
		if not dead[e] then out[#out + 1] = e end
	end
	return out
end

local function closeAll(edges: {Edge}, data: any, c: any): ({Edge}, any)
	local byFloor: { [BasePart]: {Edge} } = {}
	for _, e in ipairs(edges) do
		local b = byFloor[e.floor]
		if not b then b = {}; byFloor[e.floor] = b end
		b[#b + 1] = e
	end
	local report = {
		vertices = 0, snapped = 0, snappedCrossFloor = 0,
		mergedCollinear = 0, dropped = 0, dangling = 0, bridgedDeferred = 0,
		handover = 0,
	}
	local out: {Edge} = {}
	for part, list in pairs(byFloor) do
		local g = data.grids[part]
		local closed = closeFloor(list, g, (g and g.n) or UP, c, report)
		for _, e in ipairs(closed) do out[#out + 1] = e end
	end
	closeAcrossFloors(out, c, report)

	-- Classify what is left open. An end where walkable floor CONTINUES past
	-- it, on a different part, is a HANDOVER: the region carries on into a
	-- neighbouring slab whose own boundary picks it up elsewhere. That is not a
	-- hole and loop assembly must stitch across it — flagging it as a defect
	-- just buries the ends that really are defects.
	local function floorBeyond(e: Edge, p: Vector3): boolean
		for _, dist in ipairs({ 0.75, 1.5 }) do
			local probe = p + (p - ((e.a + e.b) * 0.5)).Unit * dist
			for part, g in pairs(data.grids) do
				if part ~= e.floor then
					for _, cell in ipairs(g.cells) do
						if math.abs(cell.pos.Y - p.Y) <= 0.5
							and (Vector3.new(cell.pos.X - probe.X, 0, cell.pos.Z - probe.Z)).Magnitude <= 1.0 then
							return true
						end
					end
				end
			end
		end
		return false
	end

	for _, e in ipairs(out) do
		if not e.closedA then
			if floorBeyond(e, e.a) then e.handoverA = true; report.handover += 1
			else report.dangling += 1 end
		end
		if not e.closedB then
			if floorBeyond(e, e.b) then e.handoverB = true; report.handover += 1
			else report.dangling += 1 end
		end
	end
	return out, report
end

--------------------------------------------------------------------------

function Clean.fromLocal(data: any, cfg: Config?)
	local c = merged(cfg)
	local t0 = os.clock()
	local samples, sstats = sampleFrontier(data, c)
	local raw = buildRuns(samples, c)
	local edges, report = closeAll(raw, data, c)
	edges = bridgeDeferred(edges, data, c, report)

	local byClass, studs = {}, {}
	for _, k in ipairs({ "wall", "seam", "dropoff", "tier" }) do byClass[k] = 0; studs[k] = 0 end
	for _, e in ipairs(edges) do
		byClass[e.class] += 1
		studs[e.class] += (e.b - e.a).Magnitude
	end
	return {
		edges = edges, samples = samples, config = c,
		stats = {
			samples = sstats, rawRuns = #raw, edges = #edges,
			byClass = byClass, studs = studs, closure = report,
			seconds = os.clock() - t0,
		},
	}
end

function Clean.build(cfg: Config?)
	local data, floorData, tree, parts = LocalGrid.build(cfg)
	return Clean.fromLocal(data, cfg), data, floorData, tree, parts
end

--------------------------------------------------------------------------

local function bar(parent: Instance, a: Vector3, b: Vector3, colour: Color3, thick: number, name: string)
	local d = b - a
	local len = d.Magnitude
	if len < 1e-3 then return end
	local p = Instance.new("Part")
	p.Anchored = true; p.CanCollide = false; p.CanQuery = false; p.CanTouch = false
	p.Size = Vector3.new(len, thick, thick)
	p.Color = colour
	p.Material = Enum.Material.Neon
	p.CFrame = CFrame.fromMatrix((a + b) * 0.5, d.Unit, UP)
	p.Name = name
	p.Parent = parent
end

-- red = wall / green = seam / cyan = dropoff / yellow = tier.
-- `showOpen` balls any endpoint that failed to close, which is the only thing
-- loop assembly will care about.
function Clean.visualize(result: any, parent: Instance?, showOpen: boolean?)
	local root = parent or workspace
	local dbg = root:FindFirstChild("NVGN_Debug")
	if not dbg then dbg = Instance.new("Folder"); dbg.Name = "NVGN_Debug"; dbg.Parent = root end
	local old = dbg:FindFirstChild("Clean")
	if old then old:Destroy() end
	local folder = Instance.new("Folder"); folder.Name = "Clean"; folder.Parent = dbg

	local colours = {
		wall = Color3.new(1, 0.15, 0.15),
		seam = Color3.new(0.2, 1, 0.35),
		dropoff = Color3.new(0.15, 0.9, 1),
		tier = Color3.new(0.95, 0.85, 0.1),
	}
	for _, e in ipairs(result.edges) do
		-- nudged toward the walkable side: an edge drawn fractionally inside a
		-- wall face looks exactly like a missing edge (v1 round 12)
		local off = UP * 0.06 - e.outDir * 0.04
		local col, nm = colours[e.class], e.class
		if e.provisional then
			-- stands in for a deferred neighbour's missing boundary: dimmed so
			-- it never reads as measured geometry
			col = col:Lerp(Color3.new(0, 0, 0), 0.55)
			nm = e.class .. "_provisional"
		end
		bar(folder, e.a + off, e.b + off, col, 0.3, nm)
		if showOpen then
			-- only genuine holes get a marker; a handover is where the region
			-- continues onto an overlapping slab, which loop assembly stitches
			local ends = {
				{ e.a, e.closedA or e.handoverA },
				{ e.b, e.closedB or e.handoverB },
			}
			for _, pair in ipairs(ends) do
				if not pair[2] then
					local ball = Instance.new("Part")
					ball.Shape = Enum.PartType.Ball
					ball.Anchored = true; ball.CanCollide = false; ball.CanQuery = false
					ball.Size = Vector3.new(0.5, 0.5, 0.5)
					ball.Color = Color3.new(1, 1, 1)
					ball.Material = Enum.Material.Neon
					ball.Position = pair[1] :: Vector3
					ball.Name = "open"
					ball.Parent = folder
				end
			end
		end
	end
	return folder
end

return Clean
